-- CREATE AUTHOR
SET DEFINE OFF;

CREATE TABLE TB_AUTHOR(
  ID NUMBER NOT NULL,
  NAME VARCHAR2(50),
  CREATED_DT TIMESTAMP,
  CREATED_BY VARCHAR2(20),
  UPDATED_DT TIMESTAMP,
  UPDATED_BY VARCHAR2(20),
  CONSTRAINT TB_AUTHOR_PK PRIMARY KEY(ID) ENABLE
);

COMMIT;

CREATE SEQUENCE "TB_AUTHOR_SEQ" MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;
COMMIT;