-- CREATE TABLE BOOK
SET DEFINE OFF;

CREATE TABLE TB_BOOK (
  ID NUMBER NOT NULL,
  ISBN VARCHAR2(30),
  INVENTORY_ID NUMBER NOT NULL,
  CREATED_DT TIMESTAMP,
  CREATED_BY VARCHAR2(20),
  UPDATED_DT TIMESTAMP,
  UPDATED_BY VARCHAR2(20),
  CONSTRAINT TB_BOOK_PK PRIMARY KEY(ID) ENABLE
);

COMMIT;

CREATE SEQUENCE "TB_BOOK_SEQ" MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;
COMMIT;