
/*-----------------------------------------------------------------------------------
**
** Source of exported db tablespace is PORTALDATA - local SIT server tablespace PORTALDATA3
** Note that table script from imported db will be from its source i.e PORTALDATA
** Advisable to use tablespace PORTALDATA
**
** Change datafile path accordingly
** CREATE BIGFILE TABLESPACE PORTALDATA DATAFILE 
**  'D:\app\Administrator\oradata\orcl\PORTALDATA.dbf' SIZE 6288M AUTOEXTEND ON NEXT 8M;
**
** Note that we can use the following create tablespace for Oracle 12c. It will auto create
** to its default directory (this is based on UAT/SIT setup at Tokio Marine).  
**
**----------------------------------------------------------------------------------- */

--DROP TABLESPACE PORTALDATA INCLUDING CONTENTS AND DATAFILES;
--COMMIT;

--CREATE BIGFILE TABLESPACE PORTALDATA DATAFILE 'PORTALDATA.dbf' SIZE 6288M AUTOEXTEND ON NEXT 8M; 
--COMMIT;

---change user and password acordingly
--DROP USER CHERIE CASCADE;
set define OFF;
alter session set "_ORACLE_SCRIPT"=true;
commit;

CREATE USER CHERIE IDENTIFIED BY "password"
 DEFAULT TABLESPACE PORTALDATA
 QUOTA UNLIMITED ON PORTALDATA;
COMMIT; 
 
GRANT ADMINISTER ANY SQL TUNING SET TO CHERIE;
GRANT ADMINISTER DATABASE TRIGGER TO CHERIE;
 
BEGIN
SYS.DBMS_RESOURCE_MANAGER_PRIVS.GRANT_SYSTEM_PRIVILEGE
  (GRANTEE_NAME   => 'CHERIE',
   PRIVILEGE_NAME => 'ADMINISTER_RESOURCE_MANAGER',
   ADMIN_OPTION   => FALSE);
END;
/ 
GRANT ADMINISTER SQL TUNING SET TO CHERIE;
GRANT ADVISOR TO CHERIE;
GRANT ALTER ANY CLUSTER TO CHERIE;
GRANT ALTER ANY DIMENSION TO CHERIE;
 
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'CHERIE',
  GRANT_OPTION => FALSE);
END;
/ 
GRANT ALTER ANY INDEX TO CHERIE;
GRANT ALTER ANY INDEXTYPE TO CHERIE;
GRANT ALTER ANY LIBRARY TO CHERIE;
GRANT ALTER ANY MATERIALIZED VIEW TO CHERIE;
GRANT ALTER ANY OPERATOR TO CHERIE;
GRANT ALTER ANY OUTLINE TO CHERIE;
GRANT ALTER ANY PROCEDURE TO CHERIE;
GRANT ALTER ANY ROLE TO CHERIE;
 
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_RULE,
  GRANTEE      => 'CHERIE',
  GRANT_OPTION => FALSE);
END;
/ 
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_RULE_SET,
  GRANTEE      => 'CHERIE',
  GRANT_OPTION => FALSE);
END;
/ 
GRANT ALTER ANY SEQUENCE TO CHERIE;
GRANT ALTER ANY SQL PROFILE TO CHERIE;
GRANT ALTER ANY TABLE TO CHERIE;
GRANT ALTER ANY TRIGGER TO CHERIE;
GRANT ALTER ANY TYPE TO CHERIE;
GRANT ALTER DATABASE TO CHERIE;
GRANT ALTER PROFILE TO CHERIE;
GRANT ALTER RESOURCE COST TO CHERIE;
GRANT ALTER ROLLBACK SEGMENT TO CHERIE;
GRANT ALTER SESSION TO CHERIE;
GRANT ALTER SYSTEM TO CHERIE;
GRANT ALTER TABLESPACE TO CHERIE;
GRANT ALTER USER TO CHERIE;
GRANT ANALYZE ANY TO CHERIE;
GRANT ANALYZE ANY DICTIONARY TO CHERIE;
GRANT AUDIT ANY TO CHERIE;
GRANT AUDIT SYSTEM TO CHERIE;
GRANT BACKUP ANY TABLE TO CHERIE;
GRANT BECOME USER TO CHERIE;
GRANT CHANGE NOTIFICATION TO CHERIE;
GRANT COMMENT ANY TABLE TO CHERIE;
GRANT CREATE ANY CLUSTER TO CHERIE;
GRANT CREATE ANY CONTEXT TO CHERIE;
GRANT CREATE ANY DIMENSION TO CHERIE;
GRANT CREATE ANY DIRECTORY TO CHERIE;
 
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'CHERIE',
  GRANT_OPTION => FALSE);
END;
/ 
GRANT CREATE ANY INDEX TO CHERIE;
GRANT CREATE ANY INDEXTYPE TO CHERIE;
GRANT CREATE ANY JOB TO CHERIE;
GRANT CREATE ANY LIBRARY TO CHERIE;
GRANT CREATE ANY MATERIALIZED VIEW TO CHERIE;
GRANT CREATE ANY OPERATOR TO CHERIE;
GRANT CREATE ANY OUTLINE TO CHERIE;
GRANT CREATE ANY PROCEDURE TO CHERIE;
 
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_RULE,
  GRANTEE      => 'CHERIE',
  GRANT_OPTION => FALSE);
END;
/ 
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_RULE_SET,
  GRANTEE      => 'CHERIE',
  GRANT_OPTION => FALSE);
END;
/ 
GRANT CREATE ANY SEQUENCE TO CHERIE;
GRANT CREATE ANY SQL PROFILE TO CHERIE;
GRANT CREATE ANY SYNONYM TO CHERIE;
GRANT CREATE ANY TABLE TO CHERIE;
GRANT CREATE ANY TRIGGER TO CHERIE;
GRANT CREATE ANY TYPE TO CHERIE;
GRANT CREATE ANY VIEW TO CHERIE;
GRANT CREATE CLUSTER TO CHERIE;
GRANT CREATE DATABASE LINK TO CHERIE;
GRANT CREATE DIMENSION TO CHERIE;
 
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_EVALUATION_CONTEXT_OBJ,
  GRANTEE      => 'CHERIE',
  GRANT_OPTION => FALSE);
END;
/ 
GRANT CREATE EXTERNAL JOB TO CHERIE;
GRANT CREATE INDEXTYPE TO CHERIE;
GRANT CREATE JOB TO CHERIE;
GRANT CREATE LIBRARY TO CHERIE;
GRANT CREATE MATERIALIZED VIEW TO CHERIE;
GRANT CREATE OPERATOR TO CHERIE;
GRANT CREATE PROCEDURE TO CHERIE;
GRANT CREATE PROFILE TO CHERIE;
GRANT CREATE PUBLIC DATABASE LINK TO CHERIE;
GRANT CREATE PUBLIC SYNONYM TO CHERIE;
GRANT CREATE ROLE TO CHERIE;
GRANT CREATE ROLLBACK SEGMENT TO CHERIE;
 
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_RULE_OBJ,
  GRANTEE      => 'CHERIE',
  GRANT_OPTION => FALSE);
END;
/ 
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_RULE_SET_OBJ,
  GRANTEE      => 'CHERIE',
  GRANT_OPTION => FALSE);
END;
/ 
GRANT CREATE SEQUENCE TO CHERIE; 
GRANT CREATE SESSION TO CHERIE;
GRANT CREATE SYNONYM TO CHERIE;
GRANT CREATE TABLE TO CHERIE;
GRANT CREATE TABLESPACE TO CHERIE;
GRANT CREATE TRIGGER TO CHERIE;
GRANT CREATE TYPE TO CHERIE;
GRANT CREATE USER TO CHERIE;
GRANT CREATE VIEW TO CHERIE;
GRANT DEBUG ANY PROCEDURE TO CHERIE;
GRANT DEBUG CONNECT SESSION TO CHERIE;
GRANT DELETE ANY TABLE TO CHERIE;
BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'DEQUEUE_ANY',
  GRANTEE      => 'CHERIE',
  ADMIN_OPTION => FALSE);
END;
/ 
GRANT DROP ANY CLUSTER TO CHERIE;
GRANT DROP ANY CONTEXT TO CHERIE;
GRANT DROP ANY DIMENSION TO CHERIE;
GRANT DROP ANY DIRECTORY TO CHERIE;
 
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'CHERIE',
  GRANT_OPTION => FALSE);
END;
/ 
GRANT DROP ANY INDEX TO CHERIE;
GRANT DROP ANY INDEXTYPE TO CHERIE;
GRANT DROP ANY LIBRARY TO CHERIE;
GRANT DROP ANY MATERIALIZED VIEW TO CHERIE;
GRANT DROP ANY OPERATOR TO CHERIE;
GRANT DROP ANY OUTLINE TO CHERIE;
GRANT DROP ANY PROCEDURE TO CHERIE;
GRANT DROP ANY ROLE TO CHERIE;
 
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_RULE,
  GRANTEE      => 'CHERIE',
  GRANT_OPTION => FALSE);
END;
/ 
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_RULE_SET,
  GRANTEE      => 'CHERIE',
  GRANT_OPTION => FALSE);
END;
/ 
GRANT DROP ANY SEQUENCE TO CHERIE;
GRANT DROP ANY SQL PROFILE TO CHERIE;
GRANT DROP ANY SYNONYM TO CHERIE;
GRANT DROP ANY TABLE TO CHERIE;
GRANT DROP ANY TRIGGER TO CHERIE;
GRANT DROP ANY TYPE TO CHERIE;
GRANT DROP ANY VIEW TO CHERIE;
GRANT DROP PROFILE TO CHERIE;
GRANT DROP PUBLIC DATABASE LINK TO CHERIE;
GRANT DROP PUBLIC SYNONYM TO CHERIE;
GRANT DROP ROLLBACK SEGMENT TO CHERIE;
GRANT DROP TABLESPACE TO CHERIE;
GRANT DROP USER TO CHERIE;
 
BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'ENQUEUE_ANY',
  GRANTEE      => 'CHERIE',
  ADMIN_OPTION => FALSE);
END;
/ 
GRANT EXECUTE ANY CLASS TO CHERIE;
 
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'CHERIE',
  GRANT_OPTION => FALSE);
END;
/ 
GRANT EXECUTE ANY INDEXTYPE TO CHERIE;
GRANT EXECUTE ANY LIBRARY TO CHERIE;
GRANT EXECUTE ANY OPERATOR TO CHERIE;
GRANT EXECUTE ANY PROCEDURE TO CHERIE;
GRANT EXECUTE ANY PROGRAM TO CHERIE;
 
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_RULE,
  GRANTEE      => 'CHERIE',
  GRANT_OPTION => FALSE);
END;
/ 
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_RULE_SET,
  GRANTEE      => 'CHERIE',
  GRANT_OPTION => FALSE);
END;
/ 
GRANT EXECUTE ANY TYPE TO CHERIE;
GRANT EXEMPT ACCESS POLICY TO CHERIE;
GRANT EXEMPT IDENTITY POLICY TO CHERIE;
GRANT EXPORT FULL DATABASE TO CHERIE;
GRANT FLASHBACK ANY TABLE TO CHERIE;
GRANT FORCE ANY TRANSACTION TO CHERIE; 
GRANT FORCE TRANSACTION TO CHERIE; 
GRANT GLOBAL QUERY REWRITE TO CHERIE; 
GRANT GRANT ANY OBJECT PRIVILEGE TO CHERIE; 
GRANT GRANT ANY PRIVILEGE TO CHERIE; 
GRANT GRANT ANY ROLE TO CHERIE; 
GRANT IMPORT FULL DATABASE TO CHERIE; 
GRANT INSERT ANY TABLE TO CHERIE; 
GRANT LOCK ANY TABLE TO CHERIE; 
GRANT MANAGE ANY FILE GROUP TO CHERIE;
 
BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'MANAGE_ANY',
  GRANTEE      => 'CHERIE',
  ADMIN_OPTION => FALSE);
END;
/ 
GRANT MANAGE FILE GROUP TO CHERIE;
GRANT MANAGE SCHEDULER TO CHERIE;
GRANT MANAGE TABLESPACE TO CHERIE;
GRANT MERGE ANY VIEW TO CHERIE;
GRANT ON COMMIT REFRESH TO CHERIE;
GRANT QUERY REWRITE TO CHERIE;
GRANT READ ANY FILE GROUP TO CHERIE;
GRANT RESTRICTED SESSION TO CHERIE;
GRANT RESUMABLE TO CHERIE;
GRANT SELECT ANY DICTIONARY TO CHERIE;
GRANT SELECT ANY SEQUENCE TO CHERIE;
GRANT SELECT ANY TABLE TO CHERIE;
GRANT SELECT ANY TRANSACTION TO CHERIE;
GRANT SYSDBA TO CHERIE;
GRANT SYSOPER TO CHERIE;
GRANT UNDER ANY TABLE TO CHERIE;
GRANT UNDER ANY TYPE TO CHERIE;
GRANT UNDER ANY VIEW TO CHERIE;
GRANT UNLIMITED TABLESPACE TO CHERIE;
GRANT UPDATE ANY TABLE TO CHERIE;
GRANT "AQ_ADMINISTRATOR_ROLE" TO CHERIE;
GRANT "AQ_USER_ROLE" TO CHERIE;
GRANT "AUTHENTICATEDUSER" TO CHERIE;
GRANT "CONNECT" TO CHERIE;
GRANT "CTXAPP" TO CHERIE;
GRANT "DBA" TO CHERIE;
GRANT "DELETE_CATALOG_ROLE" TO CHERIE;
GRANT "EJBCLIENT" TO CHERIE;
GRANT "EPORTALAPP" TO CHERIE;
GRANT "EPORTALREAD" TO CHERIE;
GRANT "EXECUTE_CATALOG_ROLE" TO CHERIE;
GRANT "EXP_FULL_DATABASE" TO CHERIE;
GRANT "GATHER_SYSTEM_STATISTICS" TO CHERIE;
GRANT "HS_ADMIN_ROLE" TO CHERIE;
GRANT "IMP_FULL_DATABASE" TO CHERIE;
GRANT "JAVADEBUGPRIV" TO CHERIE;
GRANT "JAVAIDPRIV" TO CHERIE;
GRANT "JAVASYSPRIV" TO CHERIE;
GRANT "JAVAUSERPRIV" TO CHERIE;
GRANT "JAVA_ADMIN" TO CHERIE;
GRANT "JAVA_DEPLOY" TO CHERIE;
GRANT "LOGSTDBY_ADMINISTRATOR" TO CHERIE;
GRANT "MGMT_USER" TO CHERIE;
GRANT "OEM_ADVISOR" TO CHERIE;
GRANT "OEM_MONITOR" TO CHERIE;
GRANT "OLAP_DBA" TO CHERIE;
GRANT "OLAP_USER" TO CHERIE;
GRANT "RECOVERY_CATALOG_OWNER" TO CHERIE;
GRANT "RESOURCE" TO CHERIE;
GRANT "SCHEDULER_ADMIN" TO CHERIE;
GRANT "SELECT_CATALOG_ROLE" TO CHERIE;
GRANT "WM_ADMIN_ROLE" TO CHERIE;
GRANT "XDBADMIN" TO CHERIE;
GRANT "XDBWEBSERVICES" TO CHERIE;
ALTER USER CHERIE DEFAULT ROLE NONE;
COMMIT;